FROM node:current-alpine as builder

# ENV NODE_ENV production
ENV WORK_DIR=/usr/src/app

WORKDIR $WORK_DIR
COPY web/package.json ./
RUN npm i
COPY web/. .
RUN npm run build
RUN rm -rf node_modules/

FROM nginx:stable-alpine
EXPOSE 80
#COPY ../../nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
RUN chown nginx.nginx /usr/share/nginx/html/ -R
CMD ["nginx", "-g", "daemon off;"]
